### PR TITLE
Added CALIBRATE_Z_ACCURACY with plotting

### PR DESCRIPTION
**Pull request by Clon1998**
Added CALIBRATE_Z_ACCURACY command with plotting ability. Improved terminal output while performing z_calibration.
In addition, the z_calibration outputs RAW-OFFSET now, which can be used to compare probings since its the result without the switch_offset subtracted.

Some of my plotting results:
result_calibz_1_speed_nozzle
result_calibz_1_speed_offset
result_calibz_1_speed_switch
result_calibz_1_speed_bed

### CODE REVIEW

**Comment by Clon1998** [comment]
Hey, since I noticed more people started using this plugin I figured I refactor some of the code and especially rename to axes of the plots to more reasonable values. Maybe consider merging it in order to see how the hardware of other people work with this plugin since I noticed that there is quite some variance in the quality/repeatability of measurements of the D2F microswitches.

**Comment by Clon1998** [comment]
Guess this needs some work in order to get the python script copied. I am not a shell expert so if this should be merged with this project someone has to integrate my script into the install shell script.

**Comment by Clon1998** [comment]
> Guess this needs some work in order to get the python script copied during installation/updates. I am not a shell expert so if this should be merged with this project someone has to integrate my script into the install shell script.

Guess I figured that out already... seems like I create a link to klippers scripts dir already :)

**Comment by TitusLabs** [comment]
Could you please resolve the conflicts, upgrade to Python 3 and tidy everything up? I would like to merge this :hugs:

**Comment by Clon1998** [comment]
I'll try to resolve the conflicts.
However, I can not test the code since I don't run klicky anymore.

**Pull request closed without merging**
